src/GA.XYZ.LeT.Site/Controllers/FornecedoresController.cs
using System;
using GA.XYZ.LeT.Application.IServices;
using GA.XYZ.LeT.Application.ViewModels;
using GA.XYZ.LeT.Domain.Core.Notifications;
using Microsoft.AspNetCore.Mvc;
using PagedList;

namespace GA.XYZ.LeT.Site.Controllers {

    public class FornecedoresController : BaseController
    {
        private readonly IFornecedorApplicationService _fornecedorService;
        private readonly IContatoApplicationService _contatoService;

        public FornecedoresController(IFornecedorApplicationService fornecedorService, IContatoApplicationService contatoService, IDomainNotificationHandler<DomainNotification> notifications) : base(notifications)
        {
            _fornecedorService = fornecedorService;
            _contatoService = contatoService;
        }

        [HttpGet]
        [Route("listar-fornecedores")]
        public IActionResult Index(string search, int pagina = 1){
            return View( _fornecedorService.ObterTodos(search).ToPagedList(pagina, 2));
        }

        [Route("detalhes/{id:guid}")]
        public IActionResult Details(Guid? id){

            if (id == null){
                return NotFound();
            }

            var fornecedorViewModel = _fornecedorService.ObterPorId(id.Value);
            fornecedorViewModel.Contatos = _contatoService.ObterContatoPorFornecedor(id.Value);
            if (fornecedorViewModel == null){
                return NotFound();
            }

            ViewBag.ExibirBotaoExcluir = true;
            ViewBag.ExibirBotaoEditar = false;

            return View(fornecedorViewModel);
        }

        [Route("novo-fornecedor")]
        public IActionResult Create(){
            return View(new FornecedorViewModel());
        }

        [HttpPost]
        [Route("novo-fornecedor")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FornecedorViewModel fornecedorViewModel){
            if (!ModelState.IsValid)
                return View(fornecedorViewModel);

            _fornecedorService.Registrar(fornecedorViewModel);

            if (OperacaoValida())
                ViewBag.RetornoStatus = "success,Fornecedor cadastrado com sucesso!";
            else
                ViewBag.RetornoStatus = "error,Erro ao cadastrar!";

            return View(fornecedorViewModel);
        }

        [Route("editar/{id:guid}")]
        public IActionResult Edit(Guid? id){
            if (id == null){
                return NotFound();
            }

            var fornecedorViewModel = _fornecedorService.ObterPorId(id.Value);
            fornecedorViewModel.Contatos = _contatoService.ObterContatoPorFornecedor(id.Value);
            if (fornecedorViewModel == null){
                return NotFound();
            }

            ViewBag.ExibirBotaoExcluir = false;
            ViewBag.ExibirBotaoEditar = true;

            return View(fornecedorViewModel);
        }

        [HttpPost]
        [Route("editar/{id:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(FornecedorViewModel fornecedorViewModel){

            if (!ModelState.IsValid)
                return View(fornecedorViewModel);

            _fornecedorService.Atualizar(fornecedorViewModel);

            if (OperacaoValida())
                ViewBag.RetornoStatus = "success,Fornecedor atualizado com sucesso!";
            else
                ViewBag.RetornoStatus = "error,Erro ao atualizar!";

            return View(fornecedorViewModel);
        }

        [Route("deletar/{id:guid}")]
        public IActionResult Delete(Guid? id){
            if (id == null){
                return NotFound();
            }

            var fornecedorViewModel = _fornecedorService.ObterPorId(id.Value);
            
            if (fornecedorViewModel == null){
                return NotFound();
            }

            return View(fornecedorViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [Route("deletar/{id:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id){
            _fornecedorService.Excluir(id);

            return RedirectToAction("Index");
        }





        //Contatos

        public IActionResult ListarContatos(Guid id) {
            ViewBag.FornecedorId = id;
            if (id == null) {
                return NotFound();
            }

            return PartialView("_ContatoList", _contatoService.ObterContatoPorFornecedor(id));
        }

        [Route("adicionar-contato/{id:guid}")]
        public IActionResult AdicionarContato(Guid id) {
            if (id == null) {
                return NotFound();
            }
            ViewBag.IdFornecedor = id;
            var contatoViewModel = new ContatoViewModel { IdFornecedor = id };
            return PartialView("_ContatoIncluir",contatoViewModel);
        }

        [HttpPost]
        [Route("adicionar-contato/{id:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult AdicionarContato(ContatoViewModel contatoViewModel) {
            contatoViewModel.Id = Guid.NewGuid();
            if (ModelState.IsValid) {
                _contatoService.Registrar(contatoViewModel);

                string url = Url.Action("ListarContatos", "Fornecedores", new { id = contatoViewModel.IdFornecedor });
                return Json(new { success = true, url = url });
            }

            return PartialView("_ContatoIncluir", contatoViewModel);
        }

        [Route("editar-contato/{id:guid}")]
        public IActionResult EditarContato(Guid? id) {
            if (id == null) {
                return NotFound();
            }
            return PartialView("_ContatoEditar", _contatoService.ObterPorId(id.Value));
        }

        [HttpPost]
        [Route("editar-contato/{id:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult EditarContato(ContatoViewModel contatoViewModel) {
            ModelState.Clear();
            _contatoService.Atualizar(contatoViewModel);

            if (OperacaoValida()) {
                var url = Url.Action("ListarContatos", "Fornecedores", new { id = contatoViewModel.IdFornecedor });
                return Json(new { success = true, url = url });
            }

            return PartialView("_ContatoEditar", contatoViewModel);
        }

        [Route("deletar-contato/{id:guid}")]
        public IActionResult DeletarContato(Guid? id) {
            if (id == null) {
                return NotFound();
            }

            var contatoViewModel = _contatoService.ObterPorId(id.Value);

            if (contatoViewModel == null) {
                return NotFound();
            }
            return PartialView("_ContatoDelete", contatoViewModel);
        }

        [HttpPost, ActionName("DeletarContato")]
        [Route("deletar-contato/{id:guid}")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletarContatoConfirmar(Guid id) {
            var contato = _contatoService.ObterPorId(id);
            _contatoService.Excluir(id);

            string url = Url.Action("ListarContatos", "Fornecedores", new { id = contato.IdFornecedor });
            return Json(new { success = true, url = url });
        }
    }
}

src/GA.XYZ.LeT.Site/ViewComponents/SummaryViewComponent.cs
using System.Threading.Tasks;
using GA.XYZ.LeT.Domain.Core.Notifications;
using Microsoft.AspNetCore.Mvc;

namespace GA.XYZ.LeT.Site.ViewComponents {

    public class SummaryViewComponent : ViewComponent{

        private readonly IDomainNotificationHandler<DomainNotification> _notifications;

        public SummaryViewComponent(IDomainNotificationHandler<DomainNotification> notifications) {
            this._notifications = notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync() {
            var notifications = await Task.FromResult(_notifications.GetNotifications());

            notifications.ForEach(x => ViewData.ModelState.AddModelError(string.Empty, x.Value));

            return View();
        }

    }
}

src/GA.XYZ.LeT.Site/Views/Fornecedores/Create.cshtml
@model GA.XYZ.LeT.Application.ViewModels.FornecedorViewModel

@{
    ViewData["Title"] = "Novo Fornecedor";
}


<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker3.min.css" rel="stylesheet">

<br />
<div class="container">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title"><b>@ViewData["Title"]</b></h3>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel-body">
                    <form asp-action="Create">
                        <vc:summary />
                        <div class="form-group col-md-12">
                            <label asp-for="Nome" class="control-label"></label>*
                            <input asp-for="Nome" class="form-control" placeholder="Ex: Fornecedor 123" />
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Estado" class="control-label"></label>*
                            @Html.Partial("_Estados")
                            <span asp-validation-for="Estado" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Cidade" class="control-label"></label>
                            <input asp-for="Cidade" class="form-control" />
                            <span asp-validation-for="Cidade" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-11">
                            <div class="checkbox">
                                <label>
                                    <input asp-for="Ativo" /><b>@Html.DisplayNameFor(model => model.Ativo)</b>
                                </label>
                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="PeriodoVigenciaInicio" class="control-label"></label>*
                            <input asp-for="PeriodoVigenciaInicio" type="text" asp-format="{0:dd/MM/yyyy}" placeholder="Ex: 01/01/2018" class="form-control" />
                            <span asp-validation-for="PeriodoVigenciaInicio" class="text-danger"></span>
                        </div>

                        <div class="form-group col-md-6">
                            <div id="PeriodoVigenciaFimForm">
                                <label asp-for="PeriodoVigenciaFim" class="control-label"></label>*
                                <input asp-for="PeriodoVigenciaFim" type="text" asp-format="{0:dd/MM/yyyy}" class="form-control" placeholder="Ex: 01/01/2018" />
                                <span asp-validation-for="PeriodoVigenciaFim" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            <label asp-for="ValorMaxDemanda" class="control-label"></label>
                            <input asp-for="ValorMaxDemanda" maxlength="18" type="text" class="form-control" placeholder="Ex: 123" />
                            <span asp-validation-for="ValorMaxDemanda" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-11">
                            <input type="submit" value="Adicionar" class="btn btn-success" />
                            <a asp-action="Index" class="btn btn-danger">
                                <span title="Cancelar" class=""></span> Cancelar
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div id="ContatoForm" class="row">
            <div id="ContatoTarget">
                @*@Html.Partial("_ContatoList", Model)*@
            </div>
        </div>

        <div id="myModal" class="modal fade in">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div id="myModalContent"></div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.pt-BR.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.pt.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>


    <script>
        FornecedorValidateScripts();
        FornecedorMasks();
        AjaxModal();
    </script>

    @{
        if (ViewBag.RetornoStatus != null) {
            var notificacao = ViewBag.RetornoStatus.ToString().Split(',');
            <script>
                toastr["@notificacao[0]"]("@notificacao[1]");
            </script>
        }
    }
}

src/GA.XYZ.LeT.Site/Views/Fornecedores/Delete.cshtml
@model GA.XYZ.LeT.Application.ViewModels.FornecedorViewModel

@{
    ViewData["Title"] = "Deletar fornecedor";
}

<br />

<div class="panel panel-danger">
    <div class="panel-heading">
        <h4 class="panel-title"><b>@ViewData["Title"] </b>"@Model.Nome"</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class=" col-md-12 col-lg-12 ">
                <table class="table table-user-information">
                    <tbody>
                        <tr>
                            <td><b>@Html.DisplayNameFor(model => model.Nome)</b></td>
                            <td>@Html.DisplayFor(model => model.Nome)</td>
                        </tr>
                        <tr>
                            <td><b>@Html.DisplayNameFor(model => model.Estado)</b></td>
                            <td>@Html.DisplayFor(model => model.Estado)</td>
                        </tr>
                        <tr>
                        <tr>
                            <td><b>@Html.DisplayNameFor(model => model.Cidade)</b></td>
                            <td>@Html.DisplayFor(model => model.Cidade)</td>
                        </tr>
                        <tr>
                            <td><b>@Html.DisplayNameFor(model => model.Ativo)</b></td>
                            <td>@Html.DisplayFor(model => model.Ativo)</td>
                        </tr>
                        <tr>
                            <td><b>@Html.DisplayNameFor(model => model.PeriodoVigenciaInicio)</b></td>
                            <td>@Model.PeriodoVigenciaInicio.ToString("d")</td>
                        </tr>
                        <tr>
                            <td><b>Periodo de Vigência</b></td>
                            <td>
                                @{
                                    int periodo;
                                    if (Model.Ativo == true) {
                                        periodo = (DateTime.Now - @Model.PeriodoVigenciaInicio).Days;
                                    } else {
                                        periodo = (Model.PeriodoVigenciaFim.Value - Model.PeriodoVigenciaInicio).Days;
                                    }
                                    @Html.DisplayName(periodo.ToString() + " dias");

                                }
                            </td>
                        </tr>
                        <tr>
                            <td><b>@Html.DisplayNameFor(model => model.PeriodoVigenciaFim)</b></td>
                            <td>
                                @if (Model.PeriodoVigenciaFim.HasValue) {@Model.PeriodoVigenciaFim.Value.ToString("d")}
                            </td>
                        </tr>
                        <tr>
                            <td><b>@Html.DisplayNameFor(model => model.ValorMaxDemanda)</b></td>
                            <td>@Html.DisplayFor(model => model.ValorMaxDemanda)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Deletar" class="btn btn-success" />
            <a asp-action="Index" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>

src/GA.XYZ.LeT.Site/Views/Fornecedores/Details.cshtml
@model GA.XYZ.LeT.Application.ViewModels.FornecedorViewModel

@{
    ViewData["Title"] = "Detalhes do Fornecedor";
}

<br />

<div class="container">
    <div class="row">
        <div class="">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4 class="panel-title"><b>@ViewData["Title"] </b>"@Model.Nome"</h4>
                </div>
                <div class="panel-body">
                    <div class="row ">
                        <div class=" col-md-12 col-lg-12  ">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>
                                        <td><b>@Html.DisplayNameFor(model => model.Nome)</b></td>
                                        <td>@Html.DisplayFor(model => model.Nome)</td>
                                    </tr>
                                    <tr>
                                        <td><b>@Html.DisplayNameFor(model => model.Estado)</b></td>
                                        <td>@Html.DisplayFor(model => model.Estado)</td>
                                    </tr>
                                    <tr>
                                    <tr>
                                        <td><b>@Html.DisplayNameFor(model => model.Cidade)</b></td>
                                        <td>@Html.DisplayFor(model => model.Cidade)</td>
                                    </tr>
                                    <tr>
                                        <td><b>@Html.DisplayNameFor(model => model.Ativo)</b></td>
                                        <td>@Html.DisplayFor(model => model.Ativo)</td>
                                    </tr>
                                    <tr>
                                        <td><b>@Html.DisplayNameFor(model => model.PeriodoVigenciaInicio)</b></td>
                                        <td>@Model.PeriodoVigenciaInicio.ToString("d")</td>
                                    </tr>
                                    <tr>
                                        <td><b>Periodo de Vigência</b></td>
                                        <td>
                                            @{
                                                int periodo;
                                                if (Model.Ativo == true) {
                                                    periodo = (DateTime.Now - @Model.PeriodoVigenciaInicio).Days;
                                                } else {
                                                    periodo = (Model.PeriodoVigenciaFim.Value - Model.PeriodoVigenciaInicio).Days;
                                                }
                                                @Html.DisplayName(periodo.ToString() + " dias");

                                            }
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><b>@Html.DisplayNameFor(model => model.PeriodoVigenciaFim)</b></td>
                                        <td>
                                            @if (Model.PeriodoVigenciaFim.HasValue && Model.Ativo == false) {
                                                @Model.PeriodoVigenciaFim.Value.ToString("d")
                                            } else {
                                                @Html.DisplayName(" - ")
                                            }
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><b>@Html.DisplayNameFor(model => model.ValorMaxDemanda)</b></td>
                                        <td>@Html.DisplayFor(model => model.ValorMaxDemanda)</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div id="ContatoForm">
                    <div id="ContatoTarget">
                        @Html.Partial("_ContatoList", Model)
                    </div>
                </div>

                <div id="myModal" class="modal fade in">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div id="myModalContent"></div>
                        </div>
                    </div>
                </div>

                <div class="panel-footer">
                    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">
                        <span title="Editar" class="glyphicon glyphicon-pencil"></span> Editar
                    </a>
                    <a asp-action="Index" class="btn btn-primary">
                        <span title="Voltar para lista" class=""></span> Voltar para lista
                    </a>
                </div>

            </div>
        </div>
    </div>
</div>


@section Scripts {

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.pt-BR.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.pt.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

    <script>
        ContatoMasks();
        AjaxModal();
    </script>

    @{
        if (ViewBag.RetornoStatus != null) {
            var notificacao = ViewBag.RetornoStatus.ToString().Split(',');
            <script>
                toastr["@notificacao[0]"]("@notificacao[1]");
            </script>
        }
    }
}

src/GA.XYZ.LeT.Site/Views/Fornecedores/Edit.cshtml
@model GA.XYZ.LeT.Application.ViewModels.FornecedorViewModel

@{
    ViewData["Title"] = "Editar Fornecedor";
}

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker3.min.css" rel="stylesheet">

<br />
<div class="container">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title"><b>@ViewData["Title"] </b>"@Model.Nome"</h3>
        </div>
        <div class="row">
            <div class="col">
                <div class="panel-body">
                    <form asp-action="Edit">
                        <vc:summary />

                        <input type="hidden" asp-for="Id" />
                        <div class="form-group col-md-12">
                            <label asp-for="@Model.Nome" class="control-label"></label>*
                            <input asp-for="@Model.Nome" class="form-control" />
                            <span asp-validation-for="@Model.Nome" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="@Model.Estado" class="control-label"></label>*
                            @Html.Partial("_Estados")
                            <span asp-validation-for="@Model.Estado" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="@Model.Cidade" class="control-label"></label>
                            <input asp-for="@Model.Cidade" class="form-control" />
                            <span asp-validation-for="@Model.Cidade" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <div class="checkbox">
                                <label>
                                    <input asp-for="@Model.Ativo" /> <b>@Html.DisplayNameFor(model => model.Ativo)</b>
                                </label>
                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="PeriodoVigenciaInicio" class="control-label"></label>*
                            <input asp-for="PeriodoVigenciaInicio" type="text" asp-format="{0:dd/MM/yyyy}" class="form-control" />
                            <span asp-validation-for="PeriodoVigenciaInicio" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <div id="PeriodoVigenciaFimForm">
                                <label asp-for="PeriodoVigenciaFim" class="control-label"></label>*
                                <input asp-for="PeriodoVigenciaFim" type="text" asp-format="{0:dd/MM/yyyy}" class="form-control" />
                                <span asp-validation-for="PeriodoVigenciaFim" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            <label asp-for="ValorMaxDemanda" class="control-label"></label>
                            <input asp-for="ValorMaxDemanda" maxlength="18" type="text" class="form-control" />
                            <span asp-validation-for="ValorMaxDemanda" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-11">
                            <input type="submit" value="Salvar" class="btn btn-success" />
                            <a asp-action="Index" class="btn btn-danger">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div id="ContatoForm" class="row">
            <div id="ContatoTarget">
                @Html.Partial("_ContatoList", Model)
            </div>
        </div>

        <div id="myModal" class="modal fade in">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div id="myModalContent"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.pt-BR.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.pt.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

    <script>
        FornecedorValidateScripts();
        FornecedorMasks();
        ContatoMasks();
        AjaxModal();
    </script>

    @{
        if (ViewBag.RetornoStatus != null) {
            var notificacao = ViewBag.RetornoStatus.ToString().Split(',');
            <script>
                toastr["@notificacao[0]"]("@notificacao[1]");
            </script>
        }
    }

}

src/GA.XYZ.LeT.Site/Views/Fornecedores/_Cidades.cshtml
@using GA.XYZ.LeT.Application.ViewModels
@model FornecedorViewModel

@{
    var cidades = (IEnumerable<SelectListItem>)new FornecedorViewModel().Cidades(Model.Estado);
}
<select class="form-control" asp-for="Cidade" asp-items="@cidades"></select>   

src/GA.XYZ.LeT.Site/Views/Fornecedores/_Contato.cshtml
@model GA.XYZ.LeT.Application.ViewModels.ContatoViewModel

<div class="form-horizontal">
    <input type="hidden" asp-for="IdFornecedor" />
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label asp-for="Nome" class="control-label"></label>*
        <input asp-for="Nome" class="form-control" maxlength="150" placeholder="Ex: Contato " />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>*
        <input asp-for="Email" class="form-control" maxlength="50" placeholder="Ex: contato@contato.com"/>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Telefone" class="control-label"></label>*
        <input asp-for="Telefone" type="text" class="form-control"  placeholder="Ex: (12) 3456-7890" />
        <span asp-validation-for="Telefone" class="text-danger"></span>
    </div>
</div>

src/GA.XYZ.LeT.Site/Views/Fornecedores/_ContatoEditar.cshtml
@model GA.XYZ.LeT.Application.ViewModels.ContatoViewModel

@{
    ViewData["Title"] = "Editar contato";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">×</span><span class="sr-only">Fechar</span>
    </button>
    <h4 class="modal-title"><strong>@ViewData["Title"] "@Model.Nome"</strong></h4>
</div>

<form asp-action="EditarContato">
    <div class="modal-body">
        <div class="form-horizontal">
            <vc:summary />

            <div class="modal-body">
                @Html.Partial("_Contato")
            </div>

            <div class="modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Salvar" class="btn btn-success" />
                    <input type="button" class="btn btn-danger" value="Cancelar" data-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>
</form>

src/GA.XYZ.LeT.Site/Views/Fornecedores/_ContatoIncluir.cshtml
@model GA.XYZ.LeT.Application.ViewModels.ContatoViewModel

@{
    ViewData["Title"] = "Adicionar Contato";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">×</span><span class="sr-only">Fechar</span>
    </button>
    <h4 class="modal-title"> <strong>@ViewData["Title"] </strong></h4>
</div>

<form asp-action="AdicionarContato">
    <div class="modal-body">
        <div class="form-horizontal">
            <vc:summary />

            <div class="modal-body">
                @Html.Partial("_Contato")

            </div>

            <div class="modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Adicionar Contato" class="btn btn-success" />
                    <input type="button" class="btn btn-danger" value="Cancelar" data-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>
</form>

src/GA.XYZ.LeT.Site/Views/Fornecedores/_Estados.cshtml
@using GA.XYZ.LeT.Application.ViewModels
@model FornecedorViewModel

@{
    var estados = (IEnumerable<SelectListItem>)new FornecedorViewModel().Estados();
}
<select class="form-control" asp-for="Estado" asp-items="@estados"></select>   